### PR TITLE
added some user functions, added passthru for errors

### PR DESCRIPTION
**Pull request by z0mbieparade**

### CODE REVIEW

**Comment by robertklep** [comment]
Thanks! I'll take a closer look later today or tomorrow. If possible, can you squash your commits into a single PR?

**Comment by z0mbieparade** [comment]
squashed :)

**Comment by robertklep** [comment]
Thanks again :)

The only issue I can see at first glance is an incorrect repository field in `package.json`.

**Comment by z0mbieparade** [comment]
ah crud my bad, I'm still a bit new with git.

**Comment by robertklep** [comment]
np :)

**Comment by robertklep** [comment]
Do you think it would make sense to catch 204 responses and resolve the promise using empty data? I think that's the reason you added `noReject`.

**Comment by robertklep** [comment]
@z0mbieparade merged your PR with some minor additions, and released it as 0.4.1 😀

I removed `noReject` and instead added better handling of 204 responses.

**Pull request merged**
